# Generated by Django 5.1 on 2024-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_group_searchcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
