# Generated by Django 5.1 on 2024-10-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='team1_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bet',
            name='team2_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='team1_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='team2_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
